# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Hotspot' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Hotspot
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'SwiftLocation', '~> 3.2.3'
  pod 'MotionKit'
  pod 'CodableFirebase'

end
